import type { JobCard } from "../types/Job";

export const jobCards: JobCard[] = [
  {
    id: "1",
    title: "Full Stack Developer",
    company: "Beyond Cloud Consulting Inc.",
    location: "Remote",
    workType: "Remote",
    experience: "Fresher",
    shift: "Night shift",
    responseTime: "Often responds within 2 days",
    easyApply: true,
    bookmarked: false,
  },
  {
    id: "2",
    title: "Frontend React Developer",
    company: "TechNova Solutions",
    location: "Bangalore, India",
    workType: "Hybrid",
    experience: "Experienced",
    shift: "Day shift",
    responseTime: "Responds within a week",
    easyApply: true,
    bookmarked: true,
  },
  {
    id: "3",
    title: "Backend Node.js Engineer",
    company: "CloudMatrix Pvt Ltd",
    location: "Remote",
    workType: "Remote",
    experience: "Experienced",
    shift: "Night shift",
    responseTime: "Fast response",
    easyApply: false,
    bookmarked: false,
  },
];
